# frozen_string_literal: true

# An offline stand-in for the auto-installed `validate-intent` binary.
#
# SPGD-867 made binary resolution default-on: with `SPECGUARD_VALIDATE_INTENT`
# unset, {SpecGuard::Client::ValidatorBackend::Installer} would DOWNLOAD the
# real release binary on first use. That is the production behaviour and it is
# covered by the installer specs below — but a unit suite must not depend on
# the network, so the CLI/formatter specs stub `Installer.obtain` to return a
# script this file writes, which replays the RECORDED real-binary reports in
# `spec/fixtures/validator/` (filtered to the files named on argv).
#
# The recordings are why this is faithful rather than convenient: the findings
# replayed here are what the actual binary emitted for these exact fixtures, so
# assertions written against them assert the binary's behaviour, not a
# hand-written imitation of it.
#
# The script also answers the two probes {Runner#verify!} makes (`--version`,
# `--schema-source`), reporting the digest of the real vendored schema so the
# schema-contract check lands in its `:enforced` arm by construction.
require "digest"
require "fileutils"
require "json"
require "tmpdir"

module ValidatorStub
  RECORDING_GLOB = File.expand_path("../fixtures/validator/*.json", __dir__)
  # Not a run report — a table of recorded `--schema-source` probe answers.
  EXCLUDED = ["schema-source-probes.json"].freeze

  module_function

  # Writes the stub script and returns its path. Idempotent per process.
  # @return [String]
  def install
    return @path if defined?(@path)

    dir = Dir.mktmpdir("specguard-validator-stub")
    findings_by_path = {}
    Dir[RECORDING_GLOB].reject { |p| EXCLUDED.include?(File.basename(p)) }.each do |recording|
      document = JSON.parse(File.read(recording))
      Array(document["findings"]).each do |finding|
        next unless finding.is_a?(Hash) && finding["file"].is_a?(String)

        # Recording `file` values are repo-root-relative ("spec/fixtures/…").
        absolute = File.expand_path(finding["file"], repo_root)
        findings_by_path[absolute] ||= []
        signature = [finding["line"], finding["kind"], finding["ok"], finding["errors"]]
        position = findings_by_path[absolute].index do |existing|
          [existing["line"], existing["kind"], existing["ok"], existing["errors"]] == signature
        end
        # Same finding in two recordings: keep the richer one. The `intent` key
        # arrived in SPGD-340, so an older recording of the same verdict
        # legitimately lacks it — and a replay without payloads would silently
        # degrade every passing annotation to `unannotated` downstream.
        if position.nil?
          findings_by_path[absolute] << finding
        elsif !findings_by_path[absolute][position].key?("intent") && finding.key?("intent")
          findings_by_path[absolute][position] = finding
        end
      end
    end

    findings_file = File.join(dir, "findings.json")
    File.write(findings_file, JSON.generate(findings_by_path))

    script = File.join(dir, "validate-intent-stub")
    File.write(script, <<~'RUBY')
      #!/usr/bin/env ruby
      # Auto-generated by spec/support/validator_stub.rb — replays recorded
      # real-binary reports for the files named on argv.
      require "json"
      require "digest"

      if ARGV.include?("--version")
        digest = Digest::SHA256.file(ENV.fetch("STUB_SCHEMA")).hexdigest
        puts "validate-intent 0.1.4 (go1.22.12 #{RUBY_PLATFORM}) schema sha256:#{digest}"
        exit 0
      end

      if ARGV.include?("--schema-source")
        digest = Digest::SHA256.file(ENV.fetch("STUB_SCHEMA")).hexdigest
        puts "schema <embedded schema> sha256:#{digest}"
        exit 0
      end

      recorded = JSON.parse(File.read(ENV.fetch("STUB_FINDINGS")))
      # Undo ValidatorBackend.escape_glob: [*] -> *, [?] -> ?, [[] -> [
      unescape = ->(pattern) { pattern.gsub(/\[([*?\[])\]/, '\1') }
      args = ARGV.reject { |a| a.start_with?("--") }
                .map { |a| [File.expand_path(unescape.call(a)), a] }.to_h

      # Findings are replayed against the path the caller named (args' value),
      # not the recording's own spelling — the real binary echoes the path it
      # was handed, and the report's `file` is what the CLI prints.
      findings = args.flat_map { |absolute, given| (recorded[absolute] || []).map { |f| f.merge("file" => given) } }

      # A path with no recording: the binary's `no-match` kind when the file
      # does not exist.
      args.each do |absolute, given|
        next if recorded.key?(absolute) || File.file?(absolute)

        findings << { "file" => given, "line" => nil, "ok" => false, "kind" => "no-match",
                      "errors" => ["no file(s) match '#{given}'"], "intent" => nil }
      end

      # A file that EXISTS but has no recording is validated for real: the
      # stub loads the gem's own discovery chain (which is not under test —
      # discovery stayed local at SPGD-867) and checks each payload against
      # the vendored schema with json_schemer, a DEVELOPMENT-only dependency.
      # Wording of synthesized `errors` is deliberately generic: nothing
      # asserts it; the ok/kind/intent shape is what the specs read.
      args.each do |absolute, given|
        next if recorded.key?(absolute) || !File.file?(absolute)

        require File.join(ENV.fetch("STUB_LIB"), "specguard/client")
        require "json_schemer"
        schemer ||= JSONSchemer.schema(JSON.parse(File.read(ENV.fetch("STUB_SCHEMA"))))
        SpecGuard::Client::Scanner.scan_text(File.read(absolute, encoding: "UTF-8"), file: given).map do |finding|
          if finding.extracted?
            errors = schemer.validate(finding.intent).map { |e| e["error"] || "schema violation" }
            findings << { "file" => given, "line" => finding.line, "ok" => errors.empty?,
                          "kind" => errors.empty? ? nil : "schema", "errors" => errors,
                          "intent" => finding.intent }
          else
            findings << { "file" => given, "line" => finding.line, "ok" => false,
                          "kind" => finding.kind.to_s, "errors" => [finding.problem], "intent" => nil }
          end
        end
      end

      annotations = findings.count { |f| %w[read no-match].none? { |k| f["kind"] == k } }
      report = { "mode" => "source", "summary" => { "files" => args.length, "annotations" => annotations,
                                                    "failed" => findings.count { |f| f["ok"] == false } },
                 "findings" => findings }
      puts JSON.generate(report)
      exit(report["findings"].any? { |f| f["ok"] == false } ? 1 : 0)
    RUBY
    File.chmod(0o755, script)

    lib_root = File.expand_path("../../lib", __dir__)
    @stub_env = { "STUB_FINDINGS" => findings_file, "STUB_SCHEMA" => SpecGuard::Client::SCHEMA_PATH,
                  "STUB_LIB" => lib_root }
    ENV.replace(ENV.to_h.merge(@stub_env))

    @path = script
  end

  # The env the stub script itself needs — for spec files that run the CLI or
  # the formatter in a SUBPROCESS with a replaced environment.
  # @return [Hash]
  def stub_env
    install
    @stub_env
  end

  def repo_root
    File.expand_path("../..", __dir__)
  end

  # Writes (once) and returns the offline replay stub. Specs stub the
  # default-on resolution with it themselves, e.g.
  #   before { allow(Installer).to receive(:obtain).and_return(ValidatorStub.install) }
  # — the `allow` stays in the example's scope because `allow`/`receive` are
  # example-context methods.
  # @return [String] path to the executable stub
  def install_stubbable
    install
  end
end
